# RDS 비밀번호용 K3s Secret 생성
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: default
type: Opaque
data:
  DB_PASSWORD: YWRtaW4xMjM0IQ== # Base64

# --- [Flask API Deployment] ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapi
  template:
    metadata:
      labels:
        app: myapi
    spec:
      containers:
      - name: myapi
        image: kimsewon/myapi:latest
        #image: kimsewon/myapi:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: DB_HOST
          value: terraform-20260210190831067100000001.cl0aokksg3rp.ap-northeast-2.rds.amazonaws.com # <---------- RDS 엔드포인트
        - name: DB_USER
          value: admin
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret   # 위에서 만든 Secret 이름
              key: DB_PASSWORD  # Secret data key
        - name: DB_NAME
          value: admin_db
---
# --- [API 내부 Service] ---
apiVersion: v1
kind: Service
metadata:
  name: myapi
spec:
  type: ClusterIP
  selector:
    app: myapi
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
---
# --- [★ 핵심: 보안 통로 Ingress + WAF] ---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myapi-waf-ingress
  annotations:
    # ModSecurity 활성화 주석
    nginx.ingress.kubernetes.io/enable-modsecurity: "true"
spec:
  # 위 nginx_waf 역할에서 설정한 클래스 이름 사용
  ingressClassName: nginx 
  tls:
  - secretName: waf-tls-secret # 443(HTTPS) 보호
  rules:
  - http: # host 항목을 비워서 IP 주소 접속을 허용
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: myapi
            port:

              number: 80
