---
- name: 시스템 기본 패키지 설치 (Raw)
  raw: sudo yum install -y python3 python3-pip git libselinux-python3 curl
  changed_when: false

- name: pip 업그레이드 및 K8s 라이브러리 설치 (Raw)
  raw: |
    sudo pip3 install --upgrade pip
    sudo pip3 install 'kubernetes<25.0.0' 'PyYAML<6.0.0'
  changed_when: false

- name: 인터프리터 경로 고정
  set_fact:
    ansible_python_interpreter: /usr/bin/python3
