name: 7th-room-project-deploy

on:
  push:
    branches: 
      - main
      - sh
      - Jeong
  workflow_dispatch: # 수동 실행 버튼 유지

jobs:
  #도커 빌드 및 푸시
  #docker:

  #
  terraform:
    runs-on: ubuntu-latest
    outputs:
      EC2_PUBLIC_IP: ${{ steps.get-ip.outputs.EC2_PUBLIC_IP }}
    steps:
      - uses: actions/checkout@v4
   
      - name: Terraform Running Start
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.14.4
          terraform_wrapper: false
          #명확한 주소 확인을 위해 다른 출력은 생략

      - name: Terraform Init & plan & apply
        id: apply
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

        # terraform plan이 없어도 되나요?
        # -> apply 수행 시 먼저 plan 이 자동 수행됩니다.
        run: |
          cd terraform
          terraform init
          terraform apply -auto-approve
          
      - name: Get EC2 Public IP
        id: get-ip
        run: |
         cd terraform
           # IP를 가져와서 제대로 출력되는지 로그로 확인
          TEMP_IP=$(terraform output -raw room7_public_ip)
          echo "Current IP: $TEMP_IP"
          # $GITHUB_OUTPUT에 저장
          echo "EC2_PUBLIC_IP=$TEMP_IP" >> $GITHUB_OUTPUT
  deploy:
    needs: terraform
    runs-on: ubuntu-latest

    # 조건부 실행: EC2_PUBLIC_IP가 비어있지 않은 경우에만 실행
    if : needs.terraform.outputs.EC2_PUBLIC_IP != ''
    steps:
      - uses: actions/checkout@v4
        
      # 1. SSH 키 설정 (절대 경로 및 멀티라인 처리)
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > /home/runner/.ssh/id_rsa
          chmod 400 /home/runner/.ssh/id_rsa
          
          # 서버 부팅 대기 (잠시 기다려야 SSH가 뜹니다)
          sleep 25
          
           TARGET_IP=${{ needs.terraform.outputs.EC2_PUBLIC_IP }}
          ssh-keyscan -H $TARGET_IP >> ~/.ssh/known_hosts || true

      # 2. Inventory 파일 생성 (절대 경로 사용)
      - name: Create Ansible inventory file
        run: |
         cd ansible
         echo "[k3s_cluster]" > inventory.ini
         # ~/.ssh 대신 /home/runner/.ssh 절대 경로 사용
         echo "${{ needs.terraform.outputs.EC2_PUBLIC_IP }} ansible_user=ec2-user ansible_ssh_private_key_file=/home/runner/.ssh/id_rsa" >> inventory.ini

      # 3. 앤서블 실행
      - name: Ansible Running Start
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
        run: |
          cd ansible
          ansible-playbook -i inventory.ini site.yml

      #ansible 설치 후 k3s 클러스터 배포
      #-name: k3s cluster deploy
      # run: |
